Repository Young-Project-Labs/Time-Student-Management-2024, pull requests merged in 2024-03, with the labels that each got.

#4 feat: 홈페이지 추가
  src/main/java/com/time/studentmanage/web/home/HomeController.java
  src/main/resources/templates/home.html
Labels: enhancement

#7 refactor: 테스트 환경 구축 및 엔티티 수정
  src/main/java/com/time/studentmanage/TestDataInit.java
  src/main/java/com/time/studentmanage/domain/member/Student.java
  src/test/java/com/time/studentmanage/TeacherRepositoryTest.java
  src/test/resources/application.yml
Labels: bug, enhancement

#11 feat: Parent & Student 연관관계 메서드 추가
  src/main/java/com/time/studentmanage/domain/member/Parent.java
  src/main/java/com/time/studentmanage/domain/member/Student.java
Labels: enhancement

#12 test: 피드백 CRUD 기능 구현 및 테스트, 댓글 CRUD 테스트 준비
  src/main/java/com/time/studentmanage/domain/Answer.java
  src/main/java/com/time/studentmanage/domain/Records.java
  src/main/java/com/time/studentmanage/domain/member/Student.java
  src/main/java/com/time/studentmanage/domain/member/Teacher.java
  src/main/java/com/time/studentmanage/repository/AnswerRepository.java
  src/main/java/com/time/studentmanage/repository/RecordsRepository.java
  src/test/java/com/time/studentmanage/TestUtil.java
  src/test/java/com/time/studentmanage/repository/AnswerRepositoryTest.java
  src/test/java/com/time/studentmanage/repository/RecordsRepositoryTest.java
  src/test/java/com/time/studentmanage/service/RecordServiceTest.java
Labels: enhancement, Test

#14 학생 피드백 댓글, 대댓글 CRUD 기능 구현 및 레포지터리 테스트 수행
  src/main/java/com/time/studentmanage/domain/Answer.java
  src/main/java/com/time/studentmanage/domain/enums/AnswerStatus.java
  src/main/java/com/time/studentmanage/domain/member/Teacher.java
  src/main/java/com/time/studentmanage/repository/AnswerRepository.java
  src/test/java/com/time/studentmanage/TestUtil.java
  src/test/java/com/time/studentmanage/repository/AnswerRepositoryTest.java
Labels: enhancement, Test

#17 test: Parernt & Student 테스트 코드 작성 및 빌더 패턴 적용
  src/main/java/com/time/studentmanage/config/TestDataInit.java
  src/main/java/com/time/studentmanage/domain/member/Parent.java
  src/main/java/com/time/studentmanage/domain/member/Student.java
  src/main/java/com/time/studentmanage/repository/StudentRepository.java
  src/test/java/com/time/studentmanage/repository/ParentRepositoryTest.java
  src/test/java/com/time/studentmanage/repository/RecordsRepositoryTest.java
  src/test/java/com/time/studentmanage/repository/StudentRepositoryTest.java
  src/test/java/com/time/studentmanage/repository/TeacherRepositoryTest.java
Labels: enhancement, Test

#16 refactor: 피드백, 댓글, 선생님 엔티티 엔티티에 @Builder 패턴 적용 테스트 코드 리팩토링
  src/main/java/com/time/studentmanage/config/TestDataInit.java
  src/main/java/com/time/studentmanage/domain/Answer.java
  src/main/java/com/time/studentmanage/domain/BaseTimeEntity.java
  src/main/java/com/time/studentmanage/domain/Records.java
  src/main/java/com/time/studentmanage/domain/member/Teacher.java
  src/test/java/com/time/studentmanage/TestUtil.java
  src/test/java/com/time/studentmanage/repository/AnswerRepositoryTest.java
  src/test/java/com/time/studentmanage/repository/RecordsRepositoryTest.java
Labels: Test

#19 fix: 컴파일 에러 수정 & 빌더 패턴 적용
  src/main/java/com/time/studentmanage/domain/member/Student.java
  src/main/java/com/time/studentmanage/domain/member/Teacher.java
  src/test/java/com/time/studentmanage/TestUtil.java
  src/test/java/com/time/studentmanage/repository/AnswerRepositoryTest.java
  src/test/java/com/time/studentmanage/repository/RecordsRepositoryTest.java
  src/test/java/com/time/studentmanage/repository/StudentRepositoryTest.java
Labels: bug

#22 feat: Record 서비스 기능 구현 및 서비스
  src/main/java/com/time/studentmanage/config/WebConfig.java
  src/main/java/com/time/studentmanage/domain/Answer.java
  src/main/java/com/time/studentmanage/domain/Record.java
  src/main/java/com/time/studentmanage/domain/dto/record/RecordRespDTO.java
  src/main/java/com/time/studentmanage/domain/dto/record/RecordSaveReqDTO.java
  src/main/java/com/time/studentmanage/domain/enums/RecordStatus.java
  src/main/java/com/time/studentmanage/domain/member/Student.java
  src/main/java/com/time/studentmanage/domain/member/Teacher.java
  src/main/java/com/time/studentmanage/exception/DataNotFoundException.java
  src/main/java/com/time/studentmanage/interceptor/LogInterceptor.java
  src/main/java/com/time/studentmanage/repository/AnswerRepository.java
  src/main/java/com/time/studentmanage/repository/RecordRepository.java
  src/main/java/com/time/studentmanage/repository/RecordsRepository.java
  src/main/java/com/time/studentmanage/service/AnswerService.java
  src/main/java/com/time/studentmanage/service/RecordService.java
  src/main/java/com/time/studentmanage/web/home/HomeController.java
  src/main/resources/application.yml
  src/main/resources/templates/error/500.html
  src/main/resources/templates/error/error.html
  src/test/java/com/time/studentmanage/TestUtil.java
  src/test/java/com/time/studentmanage/repository/AnswerRepositoryTest.java
  src/test/java/com/time/studentmanage/repository/RecordRepositoryTest.java
  src/test/java/com/time/studentmanage/repository/RecordsRepositoryTest.java
  src/test/java/com/time/studentmanage/repository/StudentRepositoryTest.java
  src/test/java/com/time/studentmanage/service/RecordServiceTest.java
Labels: enhancement, Test

#23 feat: StudentService & TestCode
  build.gradle
  src/main/java/com/time/studentmanage/config/AppConfig.java
  src/main/java/com/time/studentmanage/domain/member/Student.java
  src/main/java/com/time/studentmanage/dto/StudentRespDto.java
  src/main/java/com/time/studentmanage/dto/StudentSaveReqDto.java
  src/main/java/com/time/studentmanage/dto/StudentUpdateReqDto.java
  src/main/java/com/time/studentmanage/repository/StudentRepository.java
  src/main/java/com/time/studentmanage/service/StudentService.java
  src/test/java/com/time/studentmanage/TestUtil.java
  src/test/java/com/time/studentmanage/repository/StudentRepositoryTest.java
  src/test/java/com/time/studentmanage/service/StudentServiceTest.java
Labels: enhancement, Test

#30 feat: Student 로직 추가 & Teacher Service 개발
  src/main/java/com/time/studentmanage/domain/dto/student/StudentRespDto.java
  src/main/java/com/time/studentmanage/domain/dto/student/StudentSaveReqDto.java
  src/main/java/com/time/studentmanage/domain/dto/student/StudentUpdateReqDto.java
  src/main/java/com/time/studentmanage/domain/dto/teacher/TeacherRespDto.java
  src/main/java/com/time/studentmanage/domain/dto/teacher/TeacherUpdateReqDto.java
  src/main/java/com/time/studentmanage/domain/member/Student.java
  src/main/java/com/time/studentmanage/domain/member/Teacher.java
  src/main/java/com/time/studentmanage/repository/StudentRepository.java
  src/main/java/com/time/studentmanage/service/StudentService.java
  src/main/java/com/time/studentmanage/service/TeacherService.java
  src/test/java/com/time/studentmanage/TestUtil.java
  src/test/java/com/time/studentmanage/service/StudentServiceTest.java
  src/test/java/com/time/studentmanage/service/TeacherServiceTest.java
Labels: documentation, Test

#32 feat: 로그인 컨트롤러 구현
  src/main/java/com/time/studentmanage/StudentmanageApplication.java
  src/main/java/com/time/studentmanage/repository/StudentRepository.java
  src/main/java/com/time/studentmanage/repository/TeacherRepository.java
  src/main/java/com/time/studentmanage/service/LoginService.java
  src/main/java/com/time/studentmanage/web/home/HomeController.java
  src/main/java/com/time/studentmanage/web/login/LoginController.java
  src/main/java/com/time/studentmanage/web/login/LoginFormDto.java
  src/main/java/com/time/studentmanage/web/login/SessionConst.java
  src/main/resources/application.yml
  src/main/resources/errors.properties
  src/main/resources/templates/home.html
  src/main/resources/templates/login/loginPage.html
  src/main/resources/templates/template/layout/head.html
Labels: enhancement

#33 feat: 피드백 저장 시 검증 로직 기능 추가
  src/main/java/com/time/studentmanage/StudentmanageApplication.java
  src/main/java/com/time/studentmanage/config/TestDataInit.java
  src/main/java/com/time/studentmanage/domain/Record.java
  src/main/java/com/time/studentmanage/domain/dto/record/RecordRespDTO.java
  src/main/java/com/time/studentmanage/domain/dto/record/RecordSaveReqDTO.java
  src/main/java/com/time/studentmanage/service/RecordService.java
  src/main/java/com/time/studentmanage/web/RecordController.java
  src/main/resources/templates/home.html
  src/main/resources/templates/record/record_create_form.html
  src/main/resources/templates/record/record_list.html
  src/main/resources/templates/record/record_update_form.html
  src/test/java/com/time/studentmanage/repository/RecordRepositoryTest.java
  src/test/java/com/time/studentmanage/service/RecordServiceTest.java
Labels: enhancement

#36 Dto 빌더패턴 제거 및 Parent 엔티티 제거
  src/main/java/com/time/studentmanage/StudentmanageApplication.java
  src/main/java/com/time/studentmanage/config/TestDataInit.java
  src/main/java/com/time/studentmanage/domain/dto/student/StudentRespDto.java
  src/main/java/com/time/studentmanage/domain/dto/student/StudentSaveReqDto.java
  src/main/java/com/time/studentmanage/domain/dto/student/StudentUpdateReqDto.java
  src/main/java/com/time/studentmanage/domain/member/Parent.java
  src/main/java/com/time/studentmanage/domain/member/Student.java
  src/main/java/com/time/studentmanage/repository/ParentRepository.java
  src/main/java/com/time/studentmanage/service/LoginService.java
  src/main/java/com/time/studentmanage/service/StudentService.java
  src/main/java/com/time/studentmanage/web/RecordController.java
  src/test/java/com/time/studentmanage/TestUtil.java
  src/test/java/com/time/studentmanage/repository/ParentRepositoryTest.java
  src/test/java/com/time/studentmanage/service/RecordServiceTest.java
Labels: bug

#38 Student 회원가입 & 정보 수정
  src/main/java/com/time/studentmanage/StudentmanageApplication.java
  src/main/java/com/time/studentmanage/config/TestDataInit.java
  src/main/java/com/time/studentmanage/domain/Address.java
  src/main/java/com/time/studentmanage/domain/dto/student/StudentRespDto.java
  src/main/java/com/time/studentmanage/domain/dto/student/StudentSaveReqDto.java
  src/main/java/com/time/studentmanage/domain/dto/student/StudentUpdateReqDto.java
  src/main/java/com/time/studentmanage/domain/dto/teacher/TeacherRespDto.java
  src/main/java/com/time/studentmanage/domain/member/Student.java
  src/main/java/com/time/studentmanage/repository/StudentRepository.java
  src/main/java/com/time/studentmanage/repository/TeacherRepository.java
  src/main/java/com/time/studentmanage/service/LoginService.java
  src/main/java/com/time/studentmanage/service/StudentService.java
  src/main/java/com/time/studentmanage/service/TeacherService.java
  src/main/java/com/time/studentmanage/web/login/LoginController.java
  src/main/java/com/time/studentmanage/web/student/StudentApiController.java
  src/main/java/com/time/studentmanage/web/student/StudentController.java
  src/main/resources/application.yml
  src/main/resources/errors.properties
  src/main/resources/templates/home.html
  src/main/resources/templates/login/loginPage.html
  src/main/resources/templates/student/editForm.html
  src/main/resources/templates/student/joinForm.html
  src/main/resources/templates/template/layout/head.html
  src/test/java/com/time/studentmanage/TestUtil.java
  src/test/java/com/time/studentmanage/repository/StudentRepositoryTest.java
  src/test/java/com/time/studentmanage/service/StudentServiceTest.java
Labels: enhancement

#41 feat: 공통 head 및 body 속성 분리 작업
  src/main/resources/templates/home.html
  src/main/resources/templates/login/loginPage.html
  src/main/resources/templates/record/record_create_form.html
  src/main/resources/templates/record/record_list.html
  src/main/resources/templates/record/record_update_form.html
  src/main/resources/templates/student/editForm.html
  src/main/resources/templates/student/joinForm.html
  src/main/resources/templates/template/layout/base_body_component.html
  src/main/resources/templates/template/layout/base_head_component.html
Labels: enhancement
