Repository Young-Project-Labs/Time-Student-Management-2024, pull requests merged in 2024-05, with the labels that each got.

#61 선생 목록 페이징 & css(header, sidebar, footer) 적용
  src/main/java/com/time/studentmanage/domain/dto/student/SearchReqDto.java
  src/main/java/com/time/studentmanage/domain/dto/student/StudentSaveReqDto.java
  src/main/java/com/time/studentmanage/domain/dto/teacher/TeacherRespDto.java
  src/main/java/com/time/studentmanage/domain/enums/SearchType.java
  src/main/java/com/time/studentmanage/exception/SearchExControllerAdvice.java
  src/main/java/com/time/studentmanage/repository/teacher/TeacherRepository.java
  src/main/java/com/time/studentmanage/repository/teacher/TeacherRepositoryCustom.java
  src/main/java/com/time/studentmanage/repository/teacher/TeacherRepositoryCustomImpl.java
  src/main/java/com/time/studentmanage/service/MailService.java
  src/main/java/com/time/studentmanage/service/TeacherService.java
  src/main/java/com/time/studentmanage/web/student/StudentController.java
  src/main/java/com/time/studentmanage/web/teacher/TeacherController.java
  src/main/resources/static/img/kakao_button.png
  src/main/resources/templates/classroom/class_list.html
  src/main/resources/templates/home_student.html
  src/main/resources/templates/home_teacher.html
  src/main/resources/templates/login/find_id_form.html
  src/main/resources/templates/login/find_id_result.html
  src/main/resources/templates/login/login_form.html
  src/main/resources/templates/login/pwd_change_form.html
  src/main/resources/templates/record/record_create_form.html
  src/main/resources/templates/record/record_update_form.html
  src/main/resources/templates/student/edit_form.html
  src/main/resources/templates/student/join_form.html
  src/main/resources/templates/student/kakao_join_form.html
  src/main/resources/templates/student/student_list_admin.html
  src/main/resources/templates/teacher/teacher_create_form.html
  src/main/resources/templates/teacher/teacher_edit_form.html
  src/main/resources/templates/teacher/teacher_edit_form_admin.html
  src/main/resources/templates/teacher/teacher_list.html
  src/main/resources/templates/template/layout/base_body_component.html
  src/main/resources/templates/template/layout/base_head_component.html
Labels: enhancement

#64 bug: record sidebar 추가 및 버그 수정
  src/main/java/com/time/studentmanage/config/TestDataInit.java
  src/main/java/com/time/studentmanage/web/record/RecordController.java
  src/main/resources/templates/home_teacher.html
  src/main/resources/templates/record/record_create_form.html
  src/main/resources/templates/record/record_list.html
  src/main/resources/templates/student/student_list_admin.html
  src/main/resources/templates/teacher/teacher_list.html
  src/main/resources/templates/template/layout/base_body_component.html
  src/main/resources/templates/template/layout/base_head_component.html
Labels: bug

#68 경로수정 & yml 수정
  src/main/java/com/time/studentmanage/web/student/StudentController.java
  src/main/java/com/time/studentmanage/web/teacher/TeacherController.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: bug, enhancement

#71 Bug: 배포 후 발견한 오류 수정
  src/main/java/com/time/studentmanage/web/login/OAuthController.java
  src/main/resources/templates/record/record_detail.html
Labels: bug, enhancement

#74 feat: 배포 후 발견한 부분 수정 및 초기 테이블 생성 쿼리 문서 추가
  sql/init.sql
  src/main/java/com/time/studentmanage/StudentmanageApplication.java
  src/main/java/com/time/studentmanage/config/dataInit.java
  src/main/resources/templates/template/layout/base_body_component.html
Labels: documentation, enhancement

#78 선생 등록 화면 수정 & 선생 수정 로직 버그 수정 #77
  src/main/java/com/time/studentmanage/service/StudentService.java
  src/main/java/com/time/studentmanage/service/TeacherService.java
  src/main/java/com/time/studentmanage/web/student/StudentController.java
  src/main/java/com/time/studentmanage/web/teacher/TeacherController.java
  src/main/resources/templates/home_teacher.html
  src/main/resources/templates/login/find_id_form.html
  src/main/resources/templates/login/find_id_result.html
  src/main/resources/templates/login/login_form.html
  src/main/resources/templates/login/pwd_change_form.html
  src/main/resources/templates/student/edit_form.html
  src/main/resources/templates/student/join_form.html
  src/main/resources/templates/student/kakao_join_form.html
  src/main/resources/templates/student/student_list_admin.html
  src/main/resources/templates/teacher/teacher_create_form.html
  src/main/resources/templates/teacher/teacher_edit_form.html
  src/main/resources/templates/teacher/teacher_edit_form_admin.html
  src/main/resources/templates/teacher/teacher_list.html
Labels: bug

#76 refact: 데이터 베이스 컬럼 수정 및 에디터 툴바 옵션 수정 PR
  src/main/java/com/time/studentmanage/domain/record/Record.java
  src/main/resources/templates/record/record_create_form.html
  src/main/resources/templates/record/record_list.html
  src/main/resources/templates/record/record_update_form.html
Labels: documentation

#80 bug: 학생 연속 수정 시 세션 값 변경 되지 않는 버그 해결
  src/main/java/com/time/studentmanage/service/StudentService.java
  src/main/java/com/time/studentmanage/service/TeacherService.java
  src/main/java/com/time/studentmanage/web/student/StudentController.java
  src/main/java/com/time/studentmanage/web/teacher/TeacherController.java
Labels: bug
