Repository Young-Project-Labs/Time-Student-Management-2024, pull requests merged in 2024-06, with the labels that each got.

#85 feat: 학급 관리 페이지 crud 구현
  src/main/java/com/time/studentmanage/StudentmanageApplication.java
  src/main/java/com/time/studentmanage/config/RedisConfig.java
  src/main/java/com/time/studentmanage/config/RedisUtil.java
  src/main/java/com/time/studentmanage/config/TestDataInit.java
  src/main/java/com/time/studentmanage/domain/dto/classroom/ClassRoomRespDto.java
  src/main/java/com/time/studentmanage/domain/dto/classroom/ClassRoomSearchReqDto.java
  src/main/java/com/time/studentmanage/domain/dto/classroom/ClassStudentRespDto.java
  src/main/java/com/time/studentmanage/domain/dto/record/RecordRespDto.java
  src/main/java/com/time/studentmanage/domain/dto/record/RecordSaveReqDto.java
  src/main/java/com/time/studentmanage/domain/dto/record/RecordUpdateReqDto.java
  src/main/java/com/time/studentmanage/domain/dto/teacher/TeacherSearchReqDto.java
  src/main/java/com/time/studentmanage/domain/enums/SearchType.java
  src/main/java/com/time/studentmanage/domain/record/BaseTimeEntity.java
  src/main/java/com/time/studentmanage/domain/record/Record.java
  src/main/java/com/time/studentmanage/exception/RecordExControllerAdvice.java
  src/main/java/com/time/studentmanage/repository/classroom/ClassRoomRepository.java
  src/main/java/com/time/studentmanage/repository/classroom/ClassRoomRepositoryCustom.java
  src/main/java/com/time/studentmanage/repository/classroom/ClassRoomRepositoryCustomImpl.java
  src/main/java/com/time/studentmanage/repository/record/RecordRepositoryCustomImpl.java
  src/main/java/com/time/studentmanage/service/ClassRoomService.java
  src/main/java/com/time/studentmanage/service/RecordService.java
  src/main/java/com/time/studentmanage/web/classroom/ClassRoomApiController.java
  src/main/java/com/time/studentmanage/web/classroom/ClassRoomController.java
  src/main/java/com/time/studentmanage/web/record/RecordController.java
  src/main/resources/application.yml
  src/main/resources/errors.properties
  src/main/resources/templates/classroom/class_basic_info_edit_form.html
  src/main/resources/templates/classroom/class_create_form.html
  src/main/resources/templates/classroom/class_list.html
  src/main/resources/templates/classroom/class_student.html
  src/main/resources/templates/record/record_create_form.html
  src/main/resources/templates/record/record_detail.html
  src/main/resources/templates/record/record_list.html
  src/main/resources/templates/record/record_update_form.html
  src/test/java/com/time/studentmanage/TestUtil.java
  src/test/java/com/time/studentmanage/service/RecordServiceTest.java
Labels: enhancement

#87 refactor: 사이드 바 학교 목록 기능 rollback PR
  src/main/java/com/time/studentmanage/domain/dto/student/SchoolRespDto.java
  src/main/java/com/time/studentmanage/repository/student/StudentRepositoryCustom.java
  src/main/java/com/time/studentmanage/repository/student/StudentRepositoryCustomImpl.java
  src/main/java/com/time/studentmanage/repository/teacher/TeacherRepositoryCustom.java
  src/main/java/com/time/studentmanage/repository/teacher/TeacherRepositoryCustomImpl.java
  src/main/java/com/time/studentmanage/service/StudentService.java
  src/main/java/com/time/studentmanage/service/TeacherService.java
  src/main/java/com/time/studentmanage/web/teacher/TeacherController.java
  src/main/resources/templates/classroom/class_list.html
  src/main/resources/templates/home_teacher.html
  src/main/resources/templates/student/student_list_admin.html
  src/main/resources/templates/template/layout/base_body_component.html
  src/test/java/com/time/studentmanage/repository/StudentRepositoryTest.java
Labels: refactoring

#88 세션 검증 로직 리팩토링 및 어노테이션 추가
  src/main/java/com/time/studentmanage/config/Auth.java
  src/main/java/com/time/studentmanage/config/WebConfig.java
  src/main/java/com/time/studentmanage/exception/TeacherExControllerAdvice.java
  src/main/java/com/time/studentmanage/exception/TeacherExRestControllerAdvice.java
  src/main/java/com/time/studentmanage/interceptor/LogInterceptor.java
  src/main/java/com/time/studentmanage/interceptor/LoginCheckInterceptor.java
  src/main/java/com/time/studentmanage/web/login/LoginController.java
  src/main/java/com/time/studentmanage/web/record/RecordController.java
  src/main/java/com/time/studentmanage/web/student/StudentController.java
  src/main/java/com/time/studentmanage/web/teacher/TeacherApiController.java
  src/main/java/com/time/studentmanage/web/teacher/TeacherController.java
  src/main/resources/templates/error/403.html
Labels: enhancement, refactoring

#90 BugFix: 학급 수정 및 삭제 경로 매핑 오류 수정 및 sql 스크립트 수정 PR
  sql/init.sql
  src/main/java/com/time/studentmanage/web/classroom/ClassRoomController.java
  src/main/java/com/time/studentmanage/web/teacher/TeacherController.java
  src/main/resources/templates/classroom/class_basic_info_edit_form.html
  src/main/resources/templates/classroom/class_create_form.html
  src/main/resources/templates/classroom/class_list.html
  src/main/resources/templates/classroom/class_student.html
  src/test/java/com/time/studentmanage/repository/StudentRepositoryTest.java
Labels: bug, refactoring
